### ISSUE TITLE
Edison: ADC input does not work without setting Pin13 as output. 

### ISSUE THREAD

**Issue by climberhunt** [emutex/wiring-x86#4]
The SPI pins come up in an invalid state, and need some tweaking before the ADC can be read. The ADC example works because it uses Pin13 to output, but if you have a simpler sketch, then the muxing is incorrect for successful ADC reading. 
Platform: Intel Edison.

**Comment by nicopernas** [comment]
Hi,

I've updated the ADC mapping (which was wrong for Edison). Could you give it a try and see if it works now?

Thanks,
Nico.

**Comment by climberhunt** [comment]
Still not right, unfortunately. I've done a further pull request which sets the initial state of the SPI pins and changes the IIO device number from 0 to 1 for the ADS795x. That should fix it. Might be an idea in the future to detect the IIO device number rather than hardcoding it.

**Comment by climberhunt** [comment]
Now that all pins are set to a save config, the ADC now functions fine.
