### ISSUE TITLE
setPWMPeriod accepts argumets in reverse order

### ISSUE THREAD

**Issue by NetBUG** [emutex/wiring-x86#6]
Got 
`cmd = 'echo %d > /sys/class/pwm/pwmchip0/pwm%d/period' % (period, channel)
TypeError: %d format: a number is required, not NoneType`
for `gpio.setPWMPeriod(10, 20000000)`

Thus I reversed argument order and got success.
Seems it has broken somewhere inside the lib, not in Edison wrapper.
However, I don't mind.

git version of wiring-x86: commit 74e15c70ff26381cfeb798f67d86a7d2934d86ab
Hardware: Intel Edison v2 with Arduino breakout

**Comment by nicopernas** [comment]
Hi,

Thanks for your feedback. 
Edison board supports PWM output on pin 10 by setting the "swizzler" in the right position which is not supported by wiring-x86 at the moment. You can only get a PWM signal on pins 3, 5, 6 or 9.

Having said that, I see you are using Edison breakout board which I believe does not support PWM output on pin 10 at all. Take a look to [Intel's hardware guideline](https://communities.intel.com/servlet/JiveServlet/previewBody/23252-102-8-27632/edison-breakout_HG_331190-004.pdf)

Thanks,
Nico.
